### ISSUE TITLE
remove hdt-qs-benchmark

### ISSUE THREAD

**Issue by ate47** [the-qa-company/qEndpoint#316]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [ ] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [X] Other

### Task to perform

Remove the hdt-qs-benchmark directory, maybe by putting it somewhere else
