### ISSUE TITLE
wikidata prefixes need to be updated

### ISSUE THREAD

**Issue by niconical** [the-qa-company/qEndpoint#404]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [ ] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [X] Other

### Task to perform

Wikidata prefixes increased to 31 entries, while [prefixes.sparql](https://github.com/the-qa-company/qEndpoint/blob/master/wikibase/prefixes.sparql) only contains 29 of them.

Ref:
- https://www.wikidata.org/wiki/EntitySchema:E49

**Comment by ate47** [comment]
This prefix file is to [connect the endpoint to a wikibase](https://github.com/the-qa-company/qEndpoint#connecting-with-your-wikibase), not to use it like Wikidata. But it is true that we can put the Wikidata prefixes somewhere (and add them to the wikidata docker image)
